services:
  auth-service:
    build: ./auth_service
    container_name: everstory-auth-service
    restart: always
    ports:
      - "8010:8000"
    depends_on:
      - auth-db
      - redis
      - rabbitmq
    env_file:
      - ./auth_service/.env

  auth-db:
    image: postgres:latest
    container_name: everstory-auth-db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - everstory_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: everstory-redis
    restart: always
    ports:
      - "6380:6379"
    env_file:
      - .env
    volumes:
      - everstory_redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: everstory-rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - everstory_rmq_data:/var/lib/rabbitmq

volumes:
  everstory_pgdata:
  everstory_redis_data:
  everstory_rmq_data:
