services:
  auth-service:
    build: ./auth_service
    container_name: auth-service
    restart: on-failure
    ports:
      - "8011:8010"
    depends_on:
      - auth-db
      - redis
      # - rabbitmq
    env_file:
      - ./auth_service/.env

  auth-db:
    image: postgres:latest
    container_name: auth-db
    restart: on-failure
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - everstory_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: on-failure
    ports:
      - "6380:6379"
    env_file:
      - .env
    volumes:
      - everstory_redis_data:/data

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   restart: always
  #   ports:
  #     - "5673:5672"
  #     - "15673:15672"
  #   env_file:
  #     - .env
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #   volumes:
  #     - everstory_rmq_data:/var/lib/rabbitmq

  posts-service:
    build: ./posts_service
    container_name: posts-service
    restart: on-failure
    ports:
      - "8021:8020"
    depends_on:
      - posts-db
    env_file:
      - ./posts_service/.env

  posts-db:
    image: postgres:latest
    container_name: posts-db
    restart: on-failure
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - everstory_posts_pgdata:/var/lib/postgresql/data

  gateway-service:
    build: ./gateway_service
    container_name: everstory-gateway
    restart: on-failure
    ports:
      - "8001:8000"
    depends_on:
      - auth-service
      - posts-service
    env_file:
      - ./gateway_service/.env

  friendship-service:
    build: ./friendship_service
    container_name: friendship-service
    restart: on-failure
    ports:
      - "8031:8030"
    depends_on:
      - friendship-db
    env_file:
      - ./friendship_service/.env

  friendship-db:
    image: postgres:latest
    container_name: friendship-db
    restart: on-failure
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: friendship_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - everstory_friendship_pgdata:/var/lib/postgresql/data



volumes:
  everstory_pgdata:
  everstory_redis_data:
  # everstory_rmq_data:
  everstory_posts_pgdata:
  everstory_friendship_pgdata:
